### ISSUE TITLE
MIUI14进入收藏夹闪退

### ISSUE THREAD

**Issue by ZerOri** [Ehviewer-Overhauled/Ehviewer#1116]
### 复现步骤 / Step to reproduce

一点进收藏夹必闪退

### 预期行为 / Expected behaviour

进入收藏夹

### 实际行为 / Actual Behaviour

app闪退

### 应用日志 / App logs

TIME=2022-11-26-14-51-21-569

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.8.3.2
VersionCode=180023
Signature=A0:26:97:6F:97:A4:78:BB:1E:83:EE:43:C4:31:E8:AF:C6:88:36:A1

======== Runtime ========
TopActivity=com.hippo.ehviewer.ui.MainActivity
TopScene=com.hippo.ehviewer.ui.scene.GalleryDetailScene

======== DeviceInfo ========
BOARD=alioth
BOOTLOADER=unknown
SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
DEVICE=alioth
DISPLAY=SKQ1.211006.001 release-keys
FINGERPRINT=Redmi/alioth/alioth:12/RKQ1.211001.001/V13.0.9.0.SKHCNXM:user/release-keys
HARDWARE=qcom
HOST=xiaomi.eu
ID=SKQ1.211006.001
MANUFACTURER=Xiaomi
MODEL=M2012K11AG
PRODUCT=alioth
RADIO=2.5.c1-7.1-4393.37-0927_0007_9969247ed8,2.5.c1-7.1-4393.37-0927_0007_9969247ed8
TAGS=release-keys
TYPE=user
USER=builder
CODENAME=REL
INCREMENTAL=V13.0.9.0.SKHCNXM
RELEASE=12
SDK=31
MEMORY=13.9 MiB
MEMORY_NATIVE=67.6 MiB
MEMORY_MAX=512.0 MiB
MEMORY_TOTAL=11.3 GiB

======== CrashInfo ========
java.lang.ClassCastException: com.hippo.ehviewer.ui.scene.GalleryDetailScene cannot be cast to com.hippo.ehviewer.ui.scene.GalleryListScene
	at nF.K(Unknown Source:36)
	at lC.H0(Unknown Source:241)
	at com.hippo.ehviewer.ui.scene.GalleryListScene.I0(Unknown Source:68)
	at androidx.activity.b.b(Unknown Source:118)
	at androidx.activity.a.onBackPressed(Unknown Source:2)
	at com.hippo.ehviewer.ui.MainActivity.onBackPressed(Unknown Source:27)
	at android.app.Activity.onKeyUp(Unknown Source:24)
	at android.view.KeyEvent.dispatch(Unknown Source:50)
	at android.app.Activity.dispatchKeyEvent(Unknown Source:50)
	at androidx.activity.a.r(Unknown Source:0)
	at androidx.activity.a.m(Unknown Source:12)
	at n2.dispatchKeyEvent(Unknown Source:22)
	at F2.c(Unknown Source:2)
	at F2.dispatchKeyEvent(Unknown Source:19)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(Unknown Source:87)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(Unknown Source:22)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:31)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:26)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:56)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(Unknown Source:10)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(Unknown Source:6)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(Unknown Source:14)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(Unknown Source:73)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(Unknown Source:3)
	at android.view.InputEventSender.dispatchInputEventFinished(Unknown Source:0)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(Unknown Source:17)
	at android.os.Looper.loopOnce(Unknown Source:6)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

### EhViewer 版本号 / EhViewer version code

1.8.8.1

### EhViewer CI 版本 / EhViewer CI Version

1.8.8.1

### Android 系统版本 / Android version

MIUI14, android 13

### 设备型号 / Device model

红米k40

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
数据库导出份我看看？
怎么还能有预览图宽度为0的数据
先把所有收藏备份到本地再导出来我看看

**Comment by asuka-mio** [comment]
你这回这log贴的更不对了 你自己看看啥时候的了 哪个版本
