### ISSUE TITLE
无法下载种子

### ISSUE THREAD

**Issue by 7900xtx** [Ehviewer-Overhauled/Ehviewer#369]
### 复现步骤 / Step to reproduce

1.打开一个本子
2.点击“种子”选项
3.毫无反应，没有弹出下载窗口

### 预期行为 / Expected behaviour

点击“种子”后，应该弹出列有可下载种子的窗口。

### 实际行为 / Actual Behaviour

实际上点击“种子”后没有反应

### 备注 / Addition details

使用了该版本的另一个安装包重新安装，依然如此，无法下载种子。

### EhViewer 版本号 / EhViewer version code

1.7.31.0-alpha02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/txyyh/Ehviewer/actions

### Android 系统版本 / Android version

Android 9

### 设备型号 / Device model

galaxy note8 

### SoC 型号 / Soc model

骁龙835

### 应用日志 / App logs

11-04 10:42:33.510 12431 12431 D ViewRootImpl@c187f61[SettingsActivity]: dispatchDetachedFromWindow
11-04 10:42:33.510 12431 12431 D ViewRootImpl@c187f61[SettingsActivity]: Surface release. android.view.ViewRootImpl.doDie:7998 android.view.ViewRootImpl.die:7966 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.ActivityThread.handleDestroyActivity:4753 android.app.servertransaction.DestroyActivityItem.execute:39 android.app.servertransaction.TransactionExecutor.executeLifecycleState:145 
11-04 10:42:33.512 12431 12431 D InputTransport: Input channel destroyed: fd=68
11-04 10:42:33.524 12431 12431 D ViewRootImpl@765f073[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=false 0} changed=false
11-04 10:42:33.524 12431 12431 D ViewRootImpl@765f073[MainActivity]: setWindowStopped(false) old=true
11-04 10:42:33.542 12431 12431 D ViewRootImpl@765f073[MainActivity]: setWindowStopped(false) old=false
11-04 10:42:33.557 12431 12431 D ViewRootImpl@765f073[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x7 surface={valid=true 545176735744} changed=true
11-04 10:42:33.570 12431 12452 D OpenGLRenderer: eglCreateWindowSurface = 0x7eee0fe380, 0x7eef10d010
11-04 10:42:33.595 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
11-04 10:42:33.595 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:33.595 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:33.598 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:33.598 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:33.598 12431 12431 V InputMethodManager: Starting input: tba=moe.tarsin.ehviewer ic=null mNaviBarColor -520949006 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
11-04 10:42:33.598 12431 12431 D InputMethodManager: startInputInner - Id : 0
11-04 10:42:33.598 12431 12431 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
11-04 10:42:33.600 12431 12431 D InputTransport: Input channel constructed: fd=68
11-04 10:42:34.846 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
11-04 10:42:34.846 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:34.846 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:36.733 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
11-04 10:42:36.734 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:36.734 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:39.200 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 0
11-04 10:42:39.238 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 1
11-04 10:42:39.270 12431 12431 D ScrollView: initGoToTop
11-04 10:42:39.331 12431 12448 D te      : https://exhentai.org/g/2367808/06859a96fd/
11-04 10:42:39.360 12431 12431 D ScrollView:  onsize change changed 
11-04 10:42:40.437 12431 12448 D EhSSLSocketFactory: Host: exhentai.org Address: 178.175.128.252 Protocol:TLSv1.2 CipherSuite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
11-04 10:42:41.240 12431 12448 W System.err: Nu: Can't parse large preview
11-04 10:42:41.240 12431 12448 W System.err: 	at Sk.e(Unknown Source:100)
11-04 10:42:41.240 12431 12448 W System.err: 	at Sk.a(Unknown Source:738)
11-04 10:42:41.240 12431 12448 W System.err: 	at te.i(Unknown Source:87)
11-04 10:42:41.240 12431 12448 W System.err: 	at le.doInBackground(Unknown Source:540)
11-04 10:42:41.240 12431 12448 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
11-04 10:42:41.240 12431 12448 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-04 10:42:41.240 12431 12448 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-04 10:42:41.240 12431 12448 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-04 10:42:41.240 12431 12448 W System.err: 	at java.lang.Thread.run(Thread.java:764)
11-04 10:42:41.241 12431 12448 W System.err: 	at sx.run(Unknown Source:20)
11-04 10:42:41.388 12431 12431 W StaticLayout: maxLineHeight should not be -1.  maxLines:5 lineCount:5
11-04 10:42:41.388 12431 12431 W StaticLayout: maxLineHeight should not be -1.  maxLines:5 lineCount:5
11-04 10:42:41.991 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 0
11-04 10:42:42.341 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 1
11-04 10:42:42.793 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 0
11-04 10:42:42.832 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 1
11-04 10:42:42.948 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
11-04 10:42:42.948 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:42.948 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:43.164 12431 12431 D ViewRootImpl@765f073[MainActivity]: setWindowStopped(false) old=false
11-04 10:42:43.197 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
11-04 10:42:43.197 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:43.197 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:43.205 12431 12431 D ViewRootImpl@765f073[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 545176735744} changed=false
11-04 10:42:44.145 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 0
11-04 10:42:44.204 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 1
11-04 10:42:44.232 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
11-04 10:42:44.233 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:44.233 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:44.264 12431 12431 D ViewRootImpl@765f073[MainActivity]: setWindowStopped(false) old=false
11-04 10:42:44.275 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
11-04 10:42:44.276 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:44.276 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:44.284 12431 12431 D ViewRootImpl@765f073[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 545176735744} changed=false
11-04 10:42:44.860 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme key 0
11-04 10:42:44.969 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme key 1
11-04 10:42:46.271 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 0
11-04 10:42:46.328 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 1
11-04 10:42:47.371 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 0
11-04 10:42:47.397 12431 12431 D ViewRootImpl@765f073[MainActivity]: ViewPostIme pointer 1
11-04 10:42:47.446 12431 12431 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@40aac78
11-04 10:42:47.455 12431 12431 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
11-04 10:42:47.459 12431 12431 I DecorView: createDecorCaptionView >> DecorView@f9eefcb[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
11-04 10:42:47.484 12431 12431 D InputTransport: Input channel constructed: fd=87
11-04 10:42:47.484 12431 12431 D ViewRootImpl@b3e1e20[SettingsActivity]: setView = DecorView@f9eefcb[SettingsActivity] TM=true MM=false
11-04 10:42:47.485 12431 12431 D ViewRootImpl@765f073[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
11-04 10:42:47.485 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@1d7f10a[MainActivity]
11-04 10:42:47.485 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:47.490 12431 12431 D ViewRootImpl@b3e1e20[SettingsActivity]: dispatchAttachedToWindow
11-04 10:42:47.505 12431 12431 D ViewRootImpl@b3e1e20[SettingsActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x7 surface={valid=true 545138274304} changed=true
11-04 10:42:47.523 12431 12452 D OpenGLRenderer: eglCreateWindowSurface = 0x7eed7c5200, 0x7eecc5f010
11-04 10:42:47.569 12431 12431 D ViewRootImpl@b3e1e20[SettingsActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
11-04 10:42:47.569 12431 12431 D ViewRootImpl@b3e1e20[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
11-04 10:42:47.588 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@f9eefcb[SettingsActivity]
11-04 10:42:47.588 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:47.589 12431 12431 D InputMethodManager: prepareNavigationBarInfo() DecorView@f9eefcb[SettingsActivity]
11-04 10:42:47.589 12431 12431 D InputMethodManager: getNavigationBarColor() -520949006
11-04 10:42:47.589 12431 12431 V InputMethodManager: Starting input: tba=moe.tarsin.ehviewer ic=null mNaviBarColor -520949006 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
11-04 10:42:47.589 12431 12431 D InputMethodManager: startInputInner - Id : 0
11-04 10:42:47.589 12431 12431 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
11-04 10:42:47.590 12431 12431 D InputTransport: Input channel constructed: fd=93
11-04 10:42:47.590 12431 12431 D InputTransport: Input channel destroyed: fd=68

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
@7900xtx 请至少给出出现问题画廊的gid/链接

**Comment by txyyh** [comment]
@asuka-mio 要哪类日志

**Comment by 7900xtx** [comment]
> 


> @7900xtx 请至少给出出现问题画廊的gid/链接

[log-2022-11-04-10-42-56-455.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9957274/log-2022-11-04-10-42-56-455.zip)
任何画廊都无法下载种子，这是完整的日志。

**Comment by asuka-mio** [comment]
请更新1.8后再测试问题有没有解决，没有的话再reopen吧
