### ISSUE TITLE
进入详情页面时发生崩溃

### ISSUE THREAD

**Issue by finall1008** [Ehviewer-Overhauled/Ehviewer#606]
### 复现步骤 / Step to reproduce

1. 从任意列表中进入任意本子的详情页面

### 预期行为 / Expected behaviour

显示本子详情

### 实际行为 / Actual Behaviour

Ehviewer崩溃

### 备注 / Addition details

已经尝试过清除应用数据或重新安装，仍未解决问题。
另有一部小米平板 5 Pro(骁龙 870)，同样运行基于 Android 13 的 MIUI 14，同版本 Ehviewer 没有出现此问题，可以正常使用。

### EhViewer 版本号 / EhViewer version code

1.8.5.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3814412310

### Android 系统版本 / Android version

MIUI 14, Android 13

### 设备型号 / Device model

Xiaomi 12S

### SoC 型号 / Soc model

骁龙 8+ Gen 1

### 应用日志 / App logs

crash log:
```
TIME=2023-01-01-23-29-27-238

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.8.5.0
VersionCode=180028
Signature=A0:26:97:6F:97:A4:78:BB:1E:83:EE:43:C4:31:E8:AF:C6:88:36:A1

======== Runtime ========
TopActivity=com.hippo.ehviewer.ui.MainActivity
TopScene=go

======== DeviceInfo ========
BOARD=taro
BOOTLOADER=unknown
SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
DEVICE=mayfly
DISPLAY=TKQ1.220829.002 test-keys
FINGERPRINT=Xiaomi/mayfly/mayfly:13/TKQ1.220829.002/V14.0.22.12.26.DEV:user/release-keys
HARDWARE=qcom
HOST=pangu-build-component-system-31599-5kfpf-rfs6f-bs8pf
ID=TKQ1.220829.002
MANUFACTURER=Xiaomi
MODEL=2206123SC
PRODUCT=mayfly
RADIO=DE2.0.c1-7.7-15042.111226_2127_f1b20740211,DE2.0.c1-7.7-15042.111226_2127_f1b20740211
TAGS=release-keys
TYPE=user
USER=builder
CODENAME=REL
INCREMENTAL=V14.0.22.12.26.DEV
RELEASE=13
SDK=33
MEMORY=12.8 MiB
MEMORY_NATIVE=50.5 MiB
MEMORY_MAX=512.0 MiB
MEMORY_TOTAL=10.9 GiB

======== CrashInfo ========
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.optJSONObject(java.lang.String)' on a null object reference
	at gh.c(Unknown Source:6)
	at go.a1(Unknown Source:559)
	at Yn.i(Unknown Source:103)
	at Yn.a(Unknown Source:115)
	at Og.onPostExecute(Unknown Source:18)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

log:
```
--------- beginning of main
01-01 23:29:03.483 17512 30406 W libc    : Access denied finding property "vendor.migl.debug"
01-01 23:29:12.910 17512 17512 W FinalizerDaemon: type=1400 audit(0.0:131982): avc: denied { getopt } for path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=moe.tarsin.ehviewer
01-01 23:29:27.230 17512 17512 W tarsin.ehviewer: type=1400 audit(0.0:131989): avc: denied { search } for name="miuilog" dev="dm-44" ino=455148 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=moe.tarsin.ehviewer
01-01 23:29:27.230 17512 17512 W tarsin.ehviewer: type=1400 audit(0.0:131990): avc: denied { search } for name="miuilog" dev="dm-44" ino=455148 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=moe.tarsin.ehviewer
01-01 23:29:27.230 17512 17512 W tarsin.ehviewer: type=1400 audit(0.0:131991): avc: denied { search } for name="miuilog" dev="dm-44" ino=455148 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=moe.tarsin.ehviewer
01-01 23:29:27.230 17512 17512 W tarsin.ehviewer: type=1400 audit(0.0:131992): avc: denied { search } for name="miuilog" dev="dm-44" ino=455148 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=moe.tarsin.ehviewer
01-01 23:29:27.230 17512 17512 W tarsin.ehviewer: type=1400 audit(0.0:131993): avc: denied { search } for name="miuilog" dev="dm-44" ino=455148 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=moe.tarsin.ehviewer
01-01 23:29:27.230 17512 17512 W tarsin.ehviewer: type=1400 audit(0.0:131994): avc: denied { search } for name="miuilog" dev="dm-44" ino=455148 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=moe.tarsin.ehviewer
01-01 23:29:27.230 17512 17512 W tarsin.ehviewer: type=1400 audit(0.0:131995): avc: denied { getattr } for path="/data/miuilog" dev="dm-44" ino=455148 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=moe.tarsin.ehviewer
01-01 23:30:40.217 17514  3544 W libc    : Access denied finding property "vendor.migl.debug"
```

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
issue里填的1.8.5.2，日志里却是1.8.5.0？

**Comment by asuka-mio** [comment]
EhTagDatabase 那个 JSONObject现在不可能为空了，硬要获取的话错误信息应该是 kotlin.UninitializedPropertyAccessException: lateinit property 
  repository has not been initialized

**Comment by asuka-mio** [comment]
> EhTagDatabase 那个 JSONObject现在不可能为空了，硬要获取的话错误信息应该是 kotlin.UninitializedPropertyAccessException: lateinit property repository has not been initialized

而且我记得我没有不检查初始化状态就用的

**Comment by finall1008** [comment]
> issue里填的1.8.5.2，日志里却是1.8.5.0？

抱歉，因为贴上了日志之后才发现1.8.5.2更新，更新后问题依旧出现，就直接把版本号改了。现在重新放一份1.8.5.2上的crash log。
```
TIME=2023-01-02-21-19-21-745

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.8.5.2
VersionCode=180030
Signature=A0:26:97:6F:97:A4:78:BB:1E:83:EE:43:C4:31:E8:AF:C6:88:36:A1

======== Runtime ========
TopActivity=com.hippo.ehviewer.ui.MainActivity
TopScene=mo

======== DeviceInfo ========
BOARD=taro
BOOTLOADER=unknown
SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
DEVICE=mayfly
DISPLAY=TKQ1.220829.002 test-keys
FINGERPRINT=Xiaomi/mayfly/mayfly:13/TKQ1.220829.002/V14.0.22.12.26.DEV:user/release-keys
HARDWARE=qcom
HOST=pangu-build-component-system-31599-5kfpf-rfs6f-bs8pf
ID=TKQ1.220829.002
MANUFACTURER=Xiaomi
MODEL=2206123SC
PRODUCT=mayfly
RADIO=DE2.0.c1-7.7-15042.111226_2127_f1b20740211,DE2.0.c1-7.7-15042.111226_2127_f1b20740211
TAGS=release-keys
TYPE=user
USER=builder
CODENAME=REL
INCREMENTAL=V14.0.22.12.26.DEV
RELEASE=13
SDK=33
MEMORY=14.5 MiB
MEMORY_NATIVE=47.1 MiB
MEMORY_MAX=256.0 MiB
MEMORY_TOTAL=10.9 GiB

======== CrashInfo ========
RR: lateinit property tags has not been initialized
	at kh.c(Unknown Source:42)
	at mo.Z0(Unknown Source:536)
	at co.i(Unknown Source:103)
	at co.a(Unknown Source:115)
	at Rg.onPostExecute(Unknown Source:18)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by finall1008** [comment]
确实没问题了，非常感谢！
