### ISSUE TITLE
getBinding抛出NPE

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#615]
### 复现步骤 / Step to reproduce

很多行为会导致这个问题，这里写个最容易触发的

1. 从下载页面进入任意画廊
2. 删除下载项

### 预期行为 / Expected behaviour

正常

### 实际行为 / Actual Behaviour

抛出NPE

### EhViewer 版本号 / EhViewer version code

1.8.5.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3820995884

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 应用日志 / App logs

======== CrashInfo ========
java.lang.NullPointerException
	at com.hippo.ehviewer.ui.scene.SearchBarScene.getBinding(SearchBarScene.kt:37)
	at com.hippo.ehviewer.ui.scene.SearchBarScene.showSearchBar(SearchBarScene.kt:365)
	at com.hippo.ehviewer.ui.scene.GalleryListScene$GalleryListHelper.onShowView(GalleryListScene.java:1630)
	at com.hippo.view.ViewTransition.showView(ViewTransition.java:96)
	at com.hippo.view.ViewTransition.showView(ViewTransition.java:57)
	at com.hippo.widget.ContentLayout$ContentHelper.showContent(ContentLayout.java:658)
	at com.hippo.widget.ContentLayout$ContentHelper.onGetPageData(ContentLayout.java:434)
	at com.hippo.ehviewer.ui.scene.GalleryListScene.onGetGalleryListSuccess(GalleryListScene.java:1254)
	at com.hippo.ehviewer.ui.scene.GalleryListScene.-$$Nest$monGetGalleryListSuccess(Unknown Source:0)
	at com.hippo.ehviewer.ui.scene.GalleryListScene$GetGalleryListListener.onSuccess(GalleryListScene.java:1283)
	at com.hippo.ehviewer.ui.scene.GalleryListScene$GetGalleryListListener.onSuccess(GalleryListScene.java:1270)
	at com.hippo.ehviewer.client.EhClient$Task.onPostExecute(EhClient.java:190)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

======== CrashInfo ========
java.lang.NullPointerException
	at com.hippo.ehviewer.ui.scene.BaseToolbarScene.getBinding(BaseToolbarScene.kt:30)
	at com.hippo.ehviewer.ui.scene.BaseToolbarScene.setTitle(BaseToolbarScene.kt:87)
	at com.hippo.ehviewer.ui.scene.DownloadsScene.updateTitle(DownloadsScene.java:282)
	at com.hippo.ehviewer.ui.scene.DownloadsScene.updateView(DownloadsScene.java:487)
	at com.hippo.ehviewer.ui.scene.DownloadsScene.onRemove(DownloadsScene.java:775)
	at com.hippo.ehviewer.download.DownloadManager.deleteDownload(DownloadManager.java:529)
	at com.hippo.ehviewer.ui.scene.GalleryDetailScene$DeleteDialogHelper.onClick(GalleryDetailScene.java:2049)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
啊 这些都是在fragment生命周期外进行的调用 这些调用得清理掉

**Comment by asuka-mio** [comment]
算了 反正早晚得转compose 还是插几行 _binding ?: return得了
