### ISSUE TITLE
随机崩溃

### ISSUE THREAD

**Issue by duzhaokun123** [Ehviewer-Overhauled/Ehviewer#642]
### 复现步骤 / Step to reproduce

1. 打开应用随便浏览什么
2. 随机崩溃

### 预期行为 / Expected behaviour

不崩溃

### 实际行为 / Actual Behaviour

随机崩溃

### 备注 / Addition details

因为 https://github.com/Ehviewer-Overhauled/Ehviewer/blob/77a8fec790c3ef02b448bccc1d13ac9819c5c60f/app/src/main/java/com/hippo/ehviewer/gallery/ArchivePageLoader.java#L93-L108 用了`interrupt()`但https://github.com/Ehviewer-Overhauled/Ehviewer/blob/77a8fec790c3ef02b448bccc1d13ac9819c5c60f/app/src/main/java/com/hippo/ehviewer/spider/SpiderQueen.java#L1399 没有捕获·InterruptedException`导致线程崩溃

```FATAL EXCEPTION: SpiderWorker-1
Process: moe.tarsin.ehviewer.debug, PID: 12972
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:507)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.awaitTcpConnect(FastFallbackExchangeFinder.kt:155)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:69)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.downloadImage(SpiderQueen.java:1262)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.runInternal(SpiderQueen.java:1558)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.run(SpiderQueen.java:1568)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
Application "moe.tarsin.ehviewer.debug" has stopped --pid 12972```

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha03

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3859725814

### Android 系统版本 / Android version

StagOS Android 13

### 设备型号 / Device model

OnePlus 9

### SoC 型号 / Soc model

sm8350

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
啊啊 一开始就那样的
这块之后拿coroutine重写吧
