### ISSUE TITLE
画廊详情闪退

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#681]
### 复现步骤 / Step to reproduce

无法稳定复现

### 预期行为 / Expected behaviour

正常

### 实际行为 / Actual Behaviour

闪退

### 备注 / Addition details

======== CrashInfo ========
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8808)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1608)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.view.View.requestLayout(View.java:25397)
	at android.widget.TextView.checkForRelayout(TextView.java:9736)
	at android.widget.TextView.setText(TextView.java:6328)
	at android.widget.TextView.setText(TextView.java:6156)
	at android.widget.TextView.setText(TextView.java:6108)
	at com.hippo.ehviewer.ui.scene.GalleryDetailScene$bindPreviews$1$1.invokeSuspend(GalleryDetailScene.kt:721)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7eb1fa7, Dispatchers.IO]

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha05

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3922196497

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
怪 我这咋正常的
没事 我把settext放withuicontext里面就行

**Comment by asuka-mio** [comment]
主要是那块得异步inflate 要不然一下子inflate200个view得小卡一下
