### ISSUE TITLE
Migrate to KTOR CIO HTTP Client?

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#753]

**Comment by FooIbar** [comment]
代理设置选直连的话会报错

```
Caused by: java.lang.IllegalStateException: CIO engine does not currently support UNKNOWN proxies.
	at io.ktor.client.engine.cio.CIOEngine.<init>(CIOEngine.kt:50)
	at io.ktor.client.engine.cio.CIO.create(CIOCommon.kt:35)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:42)
	at com.hippo.ehviewer.EhApplication$Companion$ktorClient$2.invoke(EhApplication.kt:322)
	at com.hippo.ehviewer.EhApplication$Companion$ktorClient$2.invoke(EhApplication.kt:321)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.hippo.ehviewer.EhApplication$Companion.getKtorClient(EhApplication.kt:321)
	at com.hippo.ehviewer.spider.SpiderDenKt.<clinit>(SpiderDen.kt:53)
```

除了HTTP之外的选项全没用啊，不如删了

**Comment by asuka-mio** [comment]
> 代理设置选直连的话会报错
> 
> ```
> Caused by: java.lang.IllegalStateException: CIO engine does not currently support UNKNOWN proxies.
> 	at io.ktor.client.engine.cio.CIOEngine.<init>(CIOEngine.kt:50)
> 	at io.ktor.client.engine.cio.CIO.create(CIOCommon.kt:35)
> 	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:42)
> 	at com.hippo.ehviewer.EhApplication$Companion$ktorClient$2.invoke(EhApplication.kt:322)
> 	at com.hippo.ehviewer.EhApplication$Companion$ktorClient$2.invoke(EhApplication.kt:321)
> 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
> 	at com.hippo.ehviewer.EhApplication$Companion.getKtorClient(EhApplication.kt:321)
> 	at com.hippo.ehviewer.spider.SpiderDenKt.<clinit>(SpiderDen.kt:53)
> ```
> 
> 除了HTTP之外的选项全没用啊，不如删了

啊啊 我看了他们源码 确实
而且ktor 还没有实现自定义dns 我得抽空魔改下

**Comment by FooIbar** [comment]
自定义dns倒不着急，反正现在用ktor的图片下载也是走H@H的
