### ISSUE TITLE
图片下载失败后重试一直失败

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#789]
### 复现步骤 / Step to reproduce

1. 使用下载功能下载
2. 重试下载失败的图片

无法稳定复现

### 预期行为 / Expected behaviour

重试后正常下载

### 实际行为 / Actual Behaviour

```
Start download image 0
kotlinx.coroutines.channels.ClosedReceiveChannelException: Channel was closed
	at kotlinx.coroutines.channels.Closed.getReceiveException(AbstractChannel.kt:1108)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.resumeReceiveClosed(AbstractChannel.kt:913)
	at kotlinx.coroutines.channels.AbstractSendChannel.helpClose(AbstractChannel.kt:342)
	at kotlinx.coroutines.channels.AbstractSendChannel.close(AbstractChannel.kt:271)
	at kotlinx.coroutines.channels.ChannelCoroutine.close(Unknown Source:2)
	at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:93)
	at io.ktor.network.tls.TLSClientHandshake$input$1.invokeSuspend(TLSClientHandshake.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
End download image 0
```

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4143520017

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
应该还是cio的域名前置 hardcode servername 为0.0.0.0某些服务器还是会有意见？
暂时还是先把ktor当okhttp的delegate 吧

**Comment by FooIbar** [comment]
> 应该还是cio的域名前置 hardcode servername 为0.0.0.0某些服务器还是会有意见？

我没开域前置，而且图片下载不是走H@H吗

**Comment by asuka-mio** [comment]
> > 应该还是cio的域名前置 hardcode servername 为0.0.0.0某些服务器还是会有意见？
> 
> 我没开域前置，而且图片下载不是走H@H吗

嘶 确实 不过这个也是迁移到cio之后出现的

**Comment by asuka-mio** [comment]
不过这次换回okhttp还有一个考量 就是重写source 干脆直接下载的时候做了 架构会更合理些
skia那边对内存缓冲区还是封装成stream 读的 这样用内存映射读取的优势就不是很大了

**Comment by asuka-mio** [comment]
> 不过这次换回okhttp还有一个考量 就是重写source 干脆直接下载的时候做了 架构会更合理些 skia那边对内存缓冲区还是封装成stream 读的 这样用内存映射读取的优势就不是很大了

本来用mapping就是防止往user buffer再拷一遍
skia死活要拷一遍 我不如直接让它用fd读了
这波是skia的锅

**Comment by FooIbar** [comment]
> > > 应该还是cio的域名前置 hardcode servername 为0.0.0.0某些服务器还是会有意见？
> > 
> > 
> > 我没开域前置，而且图片下载不是走H@H吗
> 
> 嘶 确实 不过这个也是迁移到cio之后出现的

今天又遇到了，还真不是cio的问题
是某个H@H服务器连不上，重试的时候不会换源
