### ISSUE TITLE
快速滑动将导致加载失败

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#843]
### 复现步骤 / Step to reproduce

0. 重置 EhViewer
1. 打开已完成下载的画廊

https://user-images.githubusercontent.com/9050713/219882557-487ccdb1-3ab9-4427-8ea8-9c876834db7f.mp4

### 预期行为 / Expected behaviour

它应该正常加载

### 实际行为 / Actual Behaviour

加载失败

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4209673302

### Android 系统版本 / Android version

LineageOS 20

### 设备型号 / Device model

Xiaomi MI 8

### SoC 型号 / Soc model

Snapdragon 845

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
草我这倒不会加载失败，直接崩溃了
```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@b5ff69a
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:66)
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:277)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:22357)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22360)
	at androidx.viewpager.widget.DirectionalViewPager.draw(DirectionalViewPager.java:2587)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21193)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21193)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21193)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21193)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21193)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21193)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8181)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
```
只有分页模式会出现，条漫模式好像没这个问题

**Comment by Pony-CW** [comment]
这个bug，在[这个画廊](https://e-hentai.org/g/2423187/ebdd070ad5)往后逐个加载完所有图片后，往回阅读无论快慢无论模式百分百复现此bug，再往后也是亦然@FooIbar
